#!/usr/bin/env bash
set -euo pipefail

readonly HEADER='// Copyright (C) 2026 Florian Krämer
// SPDX-License-Identifier: GPL-3.0-or-later
// See LICENSE for details.
'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

mode="apply"
added=0
skipped=0
missing=0
total=0

usage() {
    cat <<'EOF'
Usage: tools/add-copyright-headers.sh [OPTIONS]

Prepends a GPL-3.0 SPDX copyright header to C# source files.

Options:
  --dry-run   List files that would be modified; do not write.
  --check     Exit 1 if any eligible file is missing the header.
  -h, --help  Show this help message.

Default: modify files in place (idempotent).
EOF
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run)
                mode="dry-run"
                ;;
            --check)
                mode="check"
                ;;
            -h | --help)
                usage
                exit 0
                ;;
            *)
                echo "Unknown option: $1" >&2
                usage >&2
                exit 2
                ;;
        esac
        shift
    done
}

should_skip_by_path() {
    local file="$1"
    case "$file" in
        */bin/* | */obj/* | *.Designer.cs | *.g.cs | *.g.i.cs | */GlobalUsings.cs)
            return 0
            ;;
    esac
    return 1
}

has_header() {
    local file="$1"
    head -n 5 "$file" | grep -qE 'Copyright \(C\)|SPDX-License-Identifier'
}

is_auto_generated() {
    local file="$1"
    head -n 5 "$file" | grep -qi '<auto-generated>'
}

discover_cs_files() {
    if git -C "$REPO_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        git -C "$REPO_ROOT" ls-files -z -- '*.cs'
        return
    fi

    find "$REPO_ROOT/src" "$REPO_ROOT/tests" -name '*.cs' \
        ! -path '*/bin/*' ! -path '*/obj/*' -print0 2>/dev/null \
        | while IFS= read -r -d '' file; do
            printf '%s\0' "${file#"$REPO_ROOT"/}"
        done
}

file_has_utf8_bom() {
    local file="$1"
    [[ "$(head -c 3 "$file" | od -An -tx1 | tr -d ' \n')" == "efbbbf" ]]
}

prepend_header() {
    local file="$1"
    local tmp
    tmp="$(mktemp "${file}.XXXXXX")"

    if file_has_utf8_bom "$file"; then
        {
            printf '\xef\xbb\xbf'
            printf '%s\n' "$HEADER"
            tail -c +4 "$file"
        } >"$tmp"
    else
        {
            printf '%s\n' "$HEADER"
            cat "$file"
        } >"$tmp"
    fi

    mv "$tmp" "$file"
}

process_file() {
    local rel="$1"
    local file="${REPO_ROOT}/${rel}"

    if [[ ! -f "$file" ]]; then
        return
    fi

    total=$((total + 1))

    if should_skip_by_path "$rel"; then
        skipped=$((skipped + 1))
        echo "skipped (generated path): ${rel}"
        return
    fi

    if is_auto_generated "$file"; then
        skipped=$((skipped + 1))
        echo "skipped (generated): ${rel}"
        return
    fi

    if has_header "$file"; then
        skipped=$((skipped + 1))
        echo "skipped (already has header): ${rel}"
        return
    fi

    case "$mode" in
        check)
            missing=$((missing + 1))
            echo "missing header: ${rel}"
            ;;
        dry-run)
            added=$((added + 1))
            echo "would add: ${rel}"
            ;;
        apply)
            prepend_header "$file"
            added=$((added + 1))
            echo "added: ${rel}"
            ;;
    esac
}

main() {
    parse_args "$@"
    cd "$REPO_ROOT"

    while IFS= read -r -d '' rel; do
        process_file "$rel"
    done < <(discover_cs_files)

    echo "Added: ${added}, Skipped: ${skipped}, Total: ${total}"

    if [[ "$mode" == "check" && "$missing" -gt 0 ]]; then
        echo "Missing headers: ${missing}" >&2
        exit 1
    fi
}

main "$@"
